<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-6L05A88V" failures="1" tests="8" name="Purchasefunctionality" time="15.074" errors="0" timestamp="2022-03-18T12:21:41 IST">
  <testcase classname="com.TestNG.AnnotationOrder" name="testcase4" time="0.005"/>
  <testcase classname="com.TestNG.dependsOn" name="login" time="0.005"/>
  <testcase classname="com.TestNG.AnnotationOrder" name="testcase3" time="0.006"/>
  <testcase classname="com.TestNG.Priority_Keyword" name="testcase1" time="0.008"/>
  <testcase classname="com.TestNG.AnnotationOrder" name="testcase3" time="0.003"/>
  <testcase classname="com.TestNG.dependsOn" name="homepage" time="0.003"/>
  <testcase classname="com.TestNG.dependsOn" name="purchase" time="0.002"/>
  <testcase classname="com.TestNG.AnnotationOrder" name="testcase1" time="15.032">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.TestNG.AnnotationOrder.testcase1() didn&amp;apos;t finish within the time-out 15000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.TestNG.AnnotationOrder.testcase1() didn't finish within the time-out 15000
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase classname="com.TestNG.AnnotationOrder" name="testcase2" time="0.0">
    <ignored/>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- Purchasefunctionality -->
